{% set name = "jenkspy" %}
{% set version = "0.1.6" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': '08d5f237d5fe3464d6e0459ac91a218fae532f34672baed609f365cffcabb41a'

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"


requirements:
  build:
    - {{ compiler('c') }}
  host:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - jenkspy

about:
  home: http://github.com/mthh/jenkspy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Compute Natural Breaks (Jenks algorythm)
  description: "Compute natural break values (Jenks algorythm) on list/tuple/numpy.ndarray of integers/floats."
  dev_url: https://github.com/mthh/jenkspy

extra:
  recipe-maintainers:
    - nickp60
